- hosts: all
  become: true
  vars:
    shell_executor_labels: 
      - 'shell-executor'
      - "gitlab-runner-{{ hostvars[inventory_hostname].ansible_distribution.lower() }}"
    docker_executor_labels:
      - 'docker-executor'
      - "gitlab-runner-{{ hostvars[inventory_hostname].ansible_distribution.lower() }}"
    docker_executor_image: "docker:latest"

  tasks:
    - name: Add gitlab-runner repo
      shell: curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.rpm.sh | sudo bash

    - name: Add Docker repository
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      run_once: yes

    - name: Install dependencies
      yum:
        name: 
          - epel-release
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
          - docker-ce
          - git
          - python3-pip
          - gitlab-runner
        state: present

    - name: Add user to the docker group
      user:
        name: ansible
        groups: docker
        append: true

    - name: Enable service
      systemd:
        name: docker
        state: started
        enabled: yes
        daemon_reload: yes

    - name: Replace docker daemon config
      copy:
        src: ./config/daemon.json
        dest: /etc/docker/daemon.json

    - name: Restart docker service
      systemd:
        name: docker
        state: restarted
        daemon_reload: yes

    - name: Install docker-compose via pip
      pip:
        name: docker-compose
        executable: pip3
    
    - name: Register gitlab shell runner
      shell: |
        gitlab-runner register -n \
        --url {{ gitlab_url }} \
        --registration-token {{ registration_token }} \
        --executor {{ executor }} \
        --description "Shell runner" \
        --tag-list {{ shell_executor_labels | join(',') }}
      when: executor == 'shell'
      run_once: true

    - name: Register gitlab docker runner
      shell: |
        gitlab-runner register -n \
        --url {{ gitlab_url }} \
        --registration-token {{ registration_token }} \
        --executor {{ executor }} \
        --description "Docker runner" \
        --docker-image {{ docker_executor_image }}
        --docker-privileged
        --tag-list {{ docker_executor_labels | join(',') }}
      when: executor == 'docker'
      run_once: true


    
