---
- include_tasks: roles/default.yml

- name: Change hostname
  hostname:
    name: k8s-master

- name: Check if cluster has already been initialized
  stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: kubeadm_ca

- name: Initialize Kubernetes cluster using kubeadm
  shell: kubeadm init --apiserver-advertise-address="{{ node_ip }}" --apiserver-cert-extra-sans="{{ node_ip }}" --node-name k8s-master --pod-network-cidr=10.244.0.0/16
  when: not kubeadm_ca.stat.exists
  run_once: yes

- name: Setup kubeconfig for vagrant user
  shell: "{{ item }}"
  with_items:
    - mkdir -p /home/vagrant/.kube
    - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
    - chown vagrant:vagrant /home/vagrant/.kube/config
  when: not kubeadm_ca.stat.exists
  run_once: yes

- name: Install Pod network
  become: false
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/2140ac876ef134e0ed5af15c65e414cf26827915/Documentation/kube-flannel.yml
  when: not kubeadm_ca.stat.exists
  run_once: yes

- name: Install Dashboard
  become: false
  shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta4/aio/deploy/recommended.yaml
  when: not kubeadm_ca.stat.exists
  run_once: yes

- name: Apply dashboard ingress config
  become: false
  shell: kubectl apply -f /home/vagrant/kubernetes/dashboard.yaml
  when: not kubeadm_ca.stat.exists
  run_once: yes

- name: Generate join command
  shell: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
  sudo: no
  copy: 
    content: "{{ join_command.stdout_lines[0] }}" 
    dest: "roles/join-command"
  delegate_to: localhost

- name: Create a 'certs' directory
  file:
    path: /home/vagrant/kubernetes/certs
    state: directory

- name: Copy client-certified-data key 
  shell: grep 'client-certificate-data' /home/vagrant/.kube/config | head -n 1 | awk '{print $2}' | base64 -d >> /home/vagrant/kubernetes/certs/kubecfg.crt

- name: Copy client-key-data
  shell: grep 'client-key-data' /home/vagrant/.kube/config | head -n 1 | awk '{print $2}' | base64 -d >> /home/vagrant/kubernetes/certs/kubecfg.key

- name: Generate pk12 key
  shell: openssl pkcs12 -export -clcerts -inkey /home/vagrant/kubernetes/certs/kubecfg.key -in /home/vagrant/kubernetes/certs/kubecfg.crt -out /home/vagrant/kubernetes/certs/kubecfg.p12 -passout pass:"1234" -name 'kubernetes-client'