---
- include_tasks: roles/default.yml

- name: Change hostname
  hostname:
    name: k8s-master

- name: Check if cluster has already been initialized
  stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: kubeadm_ca

- name: Initialize Kubernetes cluster using kubeadm
  shell: kubeadm init --apiserver-advertise-address="{{ ansible_default_ipv4.address }}" --apiserver-cert-extra-sans="{{ ansible_default_ipv4.address }}"  --node-name k8s-master
  when: not kubeadm_ca.stat.exists
  run_once: yes

- name: Setup kubeconfig for vagrant user
  shell: "{{ item }}"
  with_items:
    - mkdir -p /home/vagrant/.kube
    - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
    - chown vagrant:vagrant /home/vagrant/.kube/config
  when: not kubeadm_ca.stat.exists
  run_once: yes

- name: Install Pod network
  become_user: vagrant
  shell: kubectl create -f https://docs.projectcalico.org/v3.4/getting-started/kubernetes/installation/hosted/calico.yaml
  when: not kubeadm_ca.stat.exists
  run_once: yes

- name: Generate join command
  shell: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
  sudo: no
  copy: 
    content: "{{ join_command.stdout_lines[0] }}" 
    dest: "roles/join-command"
  delegate_to: localhost