# -*- mode: ruby -*-
# vi: set ft=ruby :

MACHINES = {
  master: {
    :box_name => "centos/7",
    :ip_addr => '192.168.12.50'
  },
  slave1: {
    :box_name => "centos/7",
    :ip_addr => '192.168.12.51'
  },
  slave2: {
    :box_name => "centos/7",
    :ip_addr => '192.168.12.52'
  }
}

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
    v.customize ["modifyvm", :id, "--audio", "none"]
  end

   MACHINES.each do |boxname, boxconfig|
      config.vm.define boxname do |box|
        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        box.vm.network "private_network", ip: boxconfig[:ip_addr]

        box.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "1024"]
        end

        box.vm.synced_folder ".", "/home/vagrant/kubernetes"
        box.vm.provision "ansible" do |ansible|
            ansible.playbook = 'site.yml'
            ansible.extra_vars = {
              node_ip: boxconfig[:ip_addr],
            }
        end
        
      end
    end
end
